"""ledgercore: generic ledger and storage primitives."""

try:
    from ledgercore._version import __version__
except ModuleNotFoundError as exc:
    if exc.name != "ledgercore._version":
        raise
    __version__ = "0.0.0+unknown"

from ledgercore.atomic import atomic_create_text, atomic_write_text
from ledgercore.config import (
    LEDGER_CONFIG_FILENAMES,
    LEDGER_LEGACY_SHARED_CONFIGS,
    LEDGER_PROJECT_LOCAL_CONFIG,
    LEDGER_PROJECT_MANIFEST,
    LedgerProjectLocator,
    ledger_config_filenames,
    locate_ledger_config,
    locate_ledger_project,
    select_project_config,
    select_tool_config,
)
from ledgercore.errors import (
    AtomicWriteError,
    FrontMatterError,
    IdFormatError,
    JsonStoreError,
    LedgerConfigError,
    LedgerCoreError,
    LedgerLayoutError,
    PathValidationError,
    StorageError,
    YamlStoreError,
)
from ledgercore.frontmatter import (
    BodyMode,
    EmptyStringStyle,
    FrontMatterRenderOptions,
    MissingFrontMatterMode,
    RemainingKeyOrder,
    ScalarStyle,
    TemplatePlaceholderMode,
    iter_markdown_files,
    iter_source_files,
    read_front_matter_document,
    render_front_matter_text,
    split_front_matter_text,
    update_front_matter_text,
    write_front_matter_document,
)
from ledgercore.hashing import (
    TextFingerprint,
    front_matter_fingerprint,
    sha256_bytes,
    sha256_text,
)
from ledgercore.ids import (
    LedgerIdFormat,
    LedgerIdParts,
    NumericIdFormat,
    next_prefixed_id,
    parse_prefixed_number,
    slugify_ref,
)
from ledgercore.refs import (
    LedgerResourceRef,
    RefStyle,
    is_resource_ref,
    normalize_kind,
    normalize_ref_token,
    parse_global_ref,
    parse_local_ref,
    parse_resource_ref,
)
from ledgercore.io import (
    content_hash,
    ensure_dir,
    merge_text,
    normalize_newlines,
    read_text,
    summarize_text,
    write_text,
)
from ledgercore.jsonio import (
    canonical_json,
    dumps_json,
    load_json_array,
    load_json_object,
    write_json,
)
from ledgercore.jsonl import (
    DuplicateKeyPolicy,
    JsonlLoadIssue,
    JsonlLoadResult,
    JsonlLoadRowsResult,
    JsonlObjectMapLoadResult,
    JsonlObjectRow,
    load_jsonl_object_map,
    load_jsonl_object_rows,
    load_jsonl_objects,
    write_jsonl_objects,
)

# Curated package-root layout facade.
# Detailed layout dataclasses (PlatformRoots, LedgerMount, LedgerProjectManifest,
# LedgerLocalConfig, LedgerRegistration, ResolvedMount, ToolConfigDefinition)
# intentionally remain under `ledgercore.layout` and must not leak into the package
# root. `derive_checkout_id` is retained at the root for 0.2.x backward
# compatibility.
from ledgercore.layout import (
    ResolvedLedgerLayout,
    derive_checkout_id,
    parse_ledger_local_config,
    parse_ledger_project_manifest,
    resolve_ledger_layout,
)
from ledgercore.path_text import (
    PunctuationProfile,
    decode_unicode_escape_literals,
    normalize_path_text,
)
from ledgercore.paths import (
    ConfigLocator,
    ensure_inside_base,
    find_config_upwards,
    is_relative_to,
    locate_config,
    relative_to_base,
    resolve_config_relative_path,
    resolve_relative_child,
    resolve_under_base,
    validate_relative_posix_path,
)
from ledgercore.time import Timespec, TimezoneStyle, utc_now_iso
from ledgercore.yamlio import load_yaml_object, write_yaml

__all__ = [
    "__version__",
    "atomic_create_text",
    "atomic_write_text",
    "LEDGER_CONFIG_FILENAMES",
    "LEDGER_PROJECT_MANIFEST",
    "LEDGER_PROJECT_LOCAL_CONFIG",
    "LEDGER_LEGACY_SHARED_CONFIGS",
    "LedgerProjectLocator",
    "ledger_config_filenames",
    "locate_ledger_config",
    "locate_ledger_project",
    "select_project_config",
    "select_tool_config",
    "AtomicWriteError",
    "FrontMatterError",
    "IdFormatError",
    "JsonStoreError",
    "LedgerConfigError",
    "LedgerLayoutError",
    "LedgerCoreError",
    "PathValidationError",
    "StorageError",
    "YamlStoreError",
    "BodyMode",
    "EmptyStringStyle",
    "FrontMatterRenderOptions",
    "MissingFrontMatterMode",
    "RemainingKeyOrder",
    "ScalarStyle",
    "TemplatePlaceholderMode",
    "iter_markdown_files",
    "iter_source_files",
    "read_front_matter_document",
    "render_front_matter_text",
    "split_front_matter_text",
    "update_front_matter_text",
    "write_front_matter_document",
    "TextFingerprint",
    "front_matter_fingerprint",
    "sha256_bytes",
    "sha256_text",
    "LedgerIdFormat",
    "LedgerIdParts",
    "NumericIdFormat",
    "next_prefixed_id",
    "parse_prefixed_number",
    "slugify_ref",
    "LedgerResourceRef",
    "RefStyle",
    "is_resource_ref",
    "normalize_kind",
    "normalize_ref_token",
    "parse_global_ref",
    "parse_local_ref",
    "parse_resource_ref",
    "content_hash",
    "ensure_dir",
    "merge_text",
    "normalize_newlines",
    "read_text",
    "summarize_text",
    "write_text",
    "canonical_json",
    "dumps_json",
    "load_json_array",
    "load_json_object",
    "write_json",
    "JsonlLoadIssue",
    "JsonlLoadResult",
    "JsonlLoadRowsResult",
    "JsonlObjectMapLoadResult",
    "JsonlObjectRow",
    "DuplicateKeyPolicy",
    "load_jsonl_object_map",
    "load_jsonl_object_rows",
    "load_jsonl_objects",
    "write_jsonl_objects",
    "parse_ledger_project_manifest",
    "parse_ledger_local_config",
    "resolve_ledger_layout",
    "ResolvedLedgerLayout",
    "derive_checkout_id",
    "PunctuationProfile",
    "decode_unicode_escape_literals",
    "normalize_path_text",
    "ConfigLocator",
    "ensure_inside_base",
    "find_config_upwards",
    "is_relative_to",
    "locate_config",
    "relative_to_base",
    "resolve_config_relative_path",
    "resolve_relative_child",
    "resolve_under_base",
    "validate_relative_posix_path",
    "utc_now_iso",
    "Timespec",
    "TimezoneStyle",
    "load_yaml_object",
    "write_yaml",
]
